# Generated by Django 3.2.8 on 2022-05-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('hight', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='low', max_length=6),
        ),
    ]
